alias aptupdate='sudo apt-get update'
alias aptupgrade='sudo apt-get upgrade'
alias aptinstall='sudo apt-get install'
alias ipynb='ipython notebook'
alias nb='ipython notebook'
alias clipboard='xclip -selection clipboard'
alias open='xdg-open'
